[package]
name = "rknn-inspect"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
rknpu2 = { git = "https://github.com/boundarybitlabs/rknpu2-rs", features = [
    "libloading",
    "rk3576",
] }
stanza = "0.5.2"
