[package]
name = "rknn-inspect"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
half = "2.6.0"
prettytable-rs = "0.10.0"
rknpu2 = { path = "../rknpu2-rs/crates/rknpu2", features = ["libloading", "rk3576"] }
