[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "rknn-inspect"
classifiers = ["Programming Language :: Rust"]
dynamic = ["version"]
license = {file = "LICENSE-MIT", name = "MIT"}

[tool.maturin]
bindings = "bin"
